[workspace]
members = ["libraries/*"]

[workspace.dependencies]
bevy = "0.14.2"
big_space = "0.7.0"
serde = "1.0.215"

[package]
name = "bevy-spacesim"
version = "0.1.0"
edition = "2021"

[dependencies]
solar_system = { path = "libraries/solar_system" }

bevy = { version = "0.14.2", features = ["serialize"] }
bevy_editor_pls = "0.9.0"
big_space = "0.7.0"
num-traits = "0.2.19"
serde = { workspace = true, features = ["derive"] }
serde_yaml = "0.9.33"
thiserror = "2.0.3"
log = "0.4.22"

[dev-dependencies]
approx = "0.5.1"

[features]
dev = ["bevy/dynamic_linking", "bevy/bevy_dev_tools", "bevy/file_watcher"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3